version: '3.8'

services:
  db:
    image: postgres:14
    container_name: gobarbercrm_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3215       # Пароль должен совпадать с config.yaml
      POSTGRES_DB: GoBarberCRM
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gobarbercrm_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=3215       # Должен совпадать с POSTGRES_PASSWORD
      - DATABASE_NAME=GoBarberCRM
      - JWT_SECRET=Graffsecretapi
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
