app:
  name: "GoBarberCRM API"
  environment: "development"
  port: 8080
  jwt_secret: "Graffsecretapi"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "3215"
  name: "GoBarberCRM"
  sslmode: "disable"

